#! /bin/sh

# /home/void/.config/wal/launch.sh /usr/share/void-artwork/desktop.png &
pgrep -x sxhkd > /dev/null || sxhkd &
mpd &
dunst &
$HOME/.config/polybar/launch.sh &
setxkbmap -option grp:alt_caps_toggle us,ar &
# albert &
# /usr/bin/emacs --daemon &
nm-applet &

xfce4-power-manager --daemon &
/usr/libexec/xfce-polkit &bash 
# /home/void/.config/bspwm/bspwm_colors.sh &bash /home/void/.config/bspwm/bspwm_colors.sh &

wpg -s $( realpath /home/void/Pictures/desktop.png) &

